### ISSUE TITLE
Keyboard interceptor ⌨️ 

### ISSUE THREAD

**Issue by MusicFreak456** [WizzWriters/spelldraw-app#22]
React to events from keyboard. 
In minimal version add `undo` action for ctrl+z shortcut and prepare scalable solution for registering to all kinds of other shortcuts in the future.

**Comment by MusicFreak456** [comment]
Not really needed to have 'blocked' label here. We can implement changing between tools without waiting.

**Comment by MusicFreak456** [comment]
To ensure robustness of this implementation, I think it would be nice to have "namespaces" or rather "contexts" of shortcuts, so it would be possible to have different behavior for the same shortcut depending on what situation user is in.

**Comment by ventus550** [comment]
Interesting. I like the idea. Still, it's difficult to say without knowing the future landscape of the application.

**Comment by ventus550** [comment]
> To ensure robustness of this implementation, I think it would be nice to have "namespaces" or rather "contexts" of shortcuts, so it would be possible to have different behavior for the same shortcut depending on what situation user is in.

Interesting. I like the idea. Still, it's difficult to say without knowing the future landscape of the application.
